title: Santeri Hukari
author:
  email: santeri.hukari@tuni.fi
  name: Santeri Hukari

description: >-
  © 2026 Santeri Hukari
baseurl: ""
url: ""

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: santerihukari
    linkedin: santerihukari
    strava: shukari
    telegram: santerihukari
    instagram: santerihukari
    27crags: santerih

# Build settings
theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
